// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: clip.proto

package clippb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmbedTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedTextRequest) Reset() {
	*x = EmbedTextRequest{}
	mi := &file_clip_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedTextRequest) ProtoMessage() {}

func (x *EmbedTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clip_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedTextRequest.ProtoReflect.Descriptor instead.
func (*EmbedTextRequest) Descriptor() ([]byte, []int) {
	return file_clip_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	RawBytes      []byte                 `protobuf:"bytes,2,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_clip_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clip_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_clip_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EmbedRequest) GetRawBytes() []byte {
	if x != nil {
		return x.RawBytes
	}
	return nil
}

func (x *EmbedRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Dim           int32                  `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_clip_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clip_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_clip_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *EmbedResponse) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *EmbedResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbedResponse) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_clip_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clip_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_clip_proto_rawDescGZIP(), []int{3}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Model         string                 `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_clip_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clip_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_clip_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HealthResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

var File_clip_proto protoreflect.FileDescriptor

const file_clip_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"clip.proto\x12\x13palettevein.clip.v1\"&\n" +
	"\x10EmbedTextRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\\\n" +
	"\fEmbedRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1b\n" +
	"\traw_bytes\x18\x02 \x01(\fR\brawBytes\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"r\n" +
	"\rEmbedResponse\x12\x1a\n" +
	"\x06vector\x18\x01 \x03(\x02B\x02\x10\x01R\x06vector\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x05R\x03dim\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x03R\tlatencyMs\"\x0f\n" +
	"\rHealthRequest\"6\n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model2\x88\x02\n" +
	"\vClipService\x12N\n" +
	"\x05Embed\x12!.palettevein.clip.v1.EmbedRequest\x1a\".palettevein.clip.v1.EmbedResponse\x12V\n" +
	"\tEmbedText\x12%.palettevein.clip.v1.EmbedTextRequest\x1a\".palettevein.clip.v1.EmbedResponse\x12Q\n" +
	"\x06Health\x12\".palettevein.clip.v1.HealthRequest\x1a#.palettevein.clip.v1.HealthResponseB$Z\"palettevein/internal/clippb;clippbb\x06proto3"

var (
	file_clip_proto_rawDescOnce sync.Once
	file_clip_proto_rawDescData []byte
)

func file_clip_proto_rawDescGZIP() []byte {
	file_clip_proto_rawDescOnce.Do(func() {
		file_clip_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clip_proto_rawDesc), len(file_clip_proto_rawDesc)))
	})
	return file_clip_proto_rawDescData
}

var file_clip_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_clip_proto_goTypes = []any{
	(*EmbedTextRequest)(nil), // 0: palettevein.clip.v1.EmbedTextRequest
	(*EmbedRequest)(nil),     // 1: palettevein.clip.v1.EmbedRequest
	(*EmbedResponse)(nil),    // 2: palettevein.clip.v1.EmbedResponse
	(*HealthRequest)(nil),    // 3: palettevein.clip.v1.HealthRequest
	(*HealthResponse)(nil),   // 4: palettevein.clip.v1.HealthResponse
}
var file_clip_proto_depIdxs = []int32{
	1, // 0: palettevein.clip.v1.ClipService.Embed:input_type -> palettevein.clip.v1.EmbedRequest
	0, // 1: palettevein.clip.v1.ClipService.EmbedText:input_type -> palettevein.clip.v1.EmbedTextRequest
	3, // 2: palettevein.clip.v1.ClipService.Health:input_type -> palettevein.clip.v1.HealthRequest
	2, // 3: palettevein.clip.v1.ClipService.Embed:output_type -> palettevein.clip.v1.EmbedResponse
	2, // 4: palettevein.clip.v1.ClipService.EmbedText:output_type -> palettevein.clip.v1.EmbedResponse
	4, // 5: palettevein.clip.v1.ClipService.Health:output_type -> palettevein.clip.v1.HealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clip_proto_init() }
func file_clip_proto_init() {
	if File_clip_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clip_proto_rawDesc), len(file_clip_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clip_proto_goTypes,
		DependencyIndexes: file_clip_proto_depIdxs,
		MessageInfos:      file_clip_proto_msgTypes,
	}.Build()
	File_clip_proto = out.File
	file_clip_proto_goTypes = nil
	file_clip_proto_depIdxs = nil
}
